// UI Component Library — barrel export
// Usage: import { UiButton, UiCard } from '@/components/ui'

export { default as UiButton }       from './UiButton.vue'
export { default as UiCard }         from './UiCard.vue'
export { default as UiInput }        from './UiInput.vue'
export { default as UiSelect }       from './UiSelect.vue'
export { default as UiField }        from './UiField.vue'
export { default as UiBadge }        from './UiBadge.vue'
export { default as UiTable }        from './UiTable.vue'
export { default as UiTabs }         from './UiTabs.vue'
export { default as UiEmptyState }   from './UiEmptyState.vue'
export { default as UiErrorState }   from './UiErrorState.vue'
export { default as UiLoadingState } from './UiLoadingState.vue'
export { default as UiStatusDot }    from './UiStatusDot.vue'
export { default as UiSwitch }       from './UiSwitch.vue'
export { default as UiDropdownMenu } from './UiDropdownMenu.vue'
export { default as UiConfirmDialog } from './UiConfirmDialog.vue'
export { default as UiIcon }         from './UiIcon.vue'
export { default as UiIconButton }   from './UiIconButton.vue'
