package store

import (
	"context"
	"encoding/json"
	"os"
	"testing"

	"entsaas/internal/bootstrap"

	"github.com/google/uuid"
)

func getTestStoreForSync(t *testing.T) *PostgresStore {
	if testing.Short() {
		t.Skip("skipping DB integration test in short mode")
	}
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgres://entsaas:secret-db-password@localhost:5432/entsaas?sslmode=disable"
	}
	masterKeyConf := bootstrap.MustParseMasterKey()
	pgStore, err := NewPostgresStore(dsn, masterKeyConf.Key, masterKeyConf.Version, 2, 1)
	if err != nil {
		t.Skipf("skipping DB integration test — no Postgres available: %v", err)
	}
	return pgStore
}

func TestPostgresStore_SyncBillingPlan(t *testing.T) {
	s := getTestStoreForSync(t)
	defer s.Close()

	ctx := context.Background()
	slug := "test-sync-" + uuid.New().String()
	name := "Test Synced Plan"
	desc := "A plan generated by integration tests"
	entitlements := map[string]any{
		"max_projects": float64(5),
		"ai_enabled":   true,
	}

	// 1. First sync - Should create the plan and insert version 1
	err := s.SyncBillingPlan(ctx, slug, name, desc, entitlements, true)
	if err != nil {
		t.Fatalf("failed first SyncBillingPlan call: %v", err)
	}

	// Verify plan was created in db
	var dbPlanID string
	var dbDisplayName string
	err = s.pool.QueryRow(ctx, "SELECT id, display_name FROM plans WHERE slug = $1", slug).Scan(&dbPlanID, &dbDisplayName)
	if err != nil {
		t.Fatalf("failed to query inserted plan: %v", err)
	}
	if dbDisplayName != name {
		t.Errorf("expected display_name %q, got %q", name, dbDisplayName)
	}

	// Verify version 1 exists in plan_versions
	var version int
	var entBytes []byte
	err = s.pool.QueryRow(ctx, "SELECT version, entitlements FROM plan_versions WHERE plan_id = $1 ORDER BY version DESC LIMIT 1", dbPlanID).Scan(&version, &entBytes)
	if err != nil {
		t.Fatalf("failed to query plan_versions: %v", err)
	}
	if version != 1 {
		t.Errorf("expected plan version to be 1, got %d", version)
	}

	var parsedEnts map[string]any
	if err := json.Unmarshal(entBytes, &parsedEnts); err != nil {
		t.Fatalf("failed to parse stored entitlements: %v", err)
	}
	if parsedEnts["max_projects"] != float64(5) || parsedEnts["ai_enabled"] != true {
		t.Errorf("stored entitlements mismatch: %v", parsedEnts)
	}

	// 2. Second sync with identical entitlements - Should NOT create a new version
	err = s.SyncBillingPlan(ctx, slug, name, desc, entitlements, true)
	if err != nil {
		t.Fatalf("failed second identical SyncBillingPlan call: %v", err)
	}

	// Verify version remains 1
	var versionAfterSecond int
	err = s.pool.QueryRow(ctx, "SELECT version FROM plan_versions WHERE plan_id = $1 ORDER BY version DESC LIMIT 1", dbPlanID).Scan(&versionAfterSecond)
	if err != nil {
		t.Fatalf("failed to query version after second sync: %v", err)
	}
	if versionAfterSecond != 1 {
		t.Errorf("expected plan version to remain 1, got %d", versionAfterSecond)
	}

	// 3. Third sync with updated entitlements - Should create version 2
	updatedEntitlements := map[string]any{
		"max_projects": float64(10), // changed
		"ai_enabled":   true,
	}
	err = s.SyncBillingPlan(ctx, slug, name, desc, updatedEntitlements, true)
	if err != nil {
		t.Fatalf("failed third SyncBillingPlan call with updated entitlements: %v", err)
	}

	// Verify version incremented to 2
	var versionAfterThird int
	err = s.pool.QueryRow(ctx, "SELECT version FROM plan_versions WHERE plan_id = $1 ORDER BY version DESC LIMIT 1", dbPlanID).Scan(&versionAfterThird)
	if err != nil {
		t.Fatalf("failed to query version after third sync: %v", err)
	}
	if versionAfterThird != 2 {
		t.Errorf("expected plan version to increment to 2, got %d", versionAfterThird)
	}

	// Clean up test data
	_, _ = s.pool.Exec(ctx, "DELETE FROM plan_versions WHERE plan_id = $1", dbPlanID)
	_, _ = s.pool.Exec(ctx, "DELETE FROM plans WHERE id = $1", dbPlanID)
}
