package billing

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rs/zerolog/log"
)

// ── Invoice Persistence Layer ────────────────────────────────────────────────
//
// InvoiceStore handles CRUD operations and provider sync for invoice metadata.
// Invoices are generated by the billing provider (Stripe, Paddle). EntSaaS stores
// metadata locally for rapid org-facing queries, audits, and off-line resilience.

// InvoiceStore manages direct database access for local invoices.
type InvoiceStore struct {
	pool *pgxpool.Pool
}

// NewInvoiceStore constructs a new InvoiceStore using pgx pool.
func NewInvoiceStore(pool *pgxpool.Pool) *InvoiceStore {
	return &InvoiceStore{pool: pool}
}

// LocalInvoice represents an invoice record in the EntSaaS database.
type LocalInvoice struct {
	ID            string         `json:"id"`
	OrgID         string         `json:"org_id"`
	ProviderID    string         `json:"provider_id"`
	ProviderName  string         `json:"provider_name"`
	Status        string         `json:"status"`
	AmountCents   int            `json:"amount_cents"`
	Currency      string         `json:"currency"`
	Description   sql.NullString `json:"description"`
	InvoiceNumber sql.NullString `json:"invoice_number"`
	PDFUrl        sql.NullString `json:"pdf_url"`
	HostedURL     sql.NullString `json:"hosted_url"`
	IsPlanChange  bool           `json:"is_plan_change"`
	PlanChangeCtx sql.NullString `json:"plan_change_ctx"`
	CreatedAt     string         `json:"created_at"`
	SyncedAt      string         `json:"synced_at"`
}

// InvoiceItem represents a single invoice in paginated search or detail views.
type InvoiceItem struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	AmountCents   int    `json:"amount_cents"`
	Currency      string `json:"currency"`
	CreatedAt     string `json:"created_at"`
	HostedURL     string `json:"hosted_url,omitempty"`
	PDFUrl        string `json:"pdf_url,omitempty"`
	Description   string `json:"description,omitempty"`
	InvoiceNumber string `json:"invoice_number,omitempty"`
	IsPlanChange  bool   `json:"is_plan_change,omitempty"`
	PlanChangeCtx string `json:"plan_change_ctx,omitempty"`
}

// InvoicePage represents a paginated list of invoice items.
type InvoicePage struct {
	Invoices []InvoiceItem `json:"invoices"`
	Total    int           `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
	HasMore  bool          `json:"has_more"`
}

// UpsertInvoice saves an invoice record locally.
// Uses provider_id as conflict target for idempotency.
func (s *InvoiceStore) UpsertInvoice(ctx context.Context, inv LocalInvoice) error {
	query := `
		INSERT INTO invoices (org_id, provider_id, provider_name, status, amount_cents, currency,
			description, invoice_number, pdf_url, hosted_url, is_plan_change, plan_change_ctx, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		ON CONFLICT (provider_id)
		DO UPDATE SET
			status = EXCLUDED.status,
			amount_cents = EXCLUDED.amount_cents,
			pdf_url = EXCLUDED.pdf_url,
			hosted_url = EXCLUDED.hosted_url,
			is_plan_change = EXCLUDED.is_plan_change,
			plan_change_ctx = EXCLUDED.plan_change_ctx,
			synced_at = now()
	`
	_, err := s.pool.Exec(ctx, query,
		inv.OrgID, inv.ProviderID, inv.ProviderName, inv.Status, inv.AmountCents, inv.Currency,
		inv.Description, inv.InvoiceNumber, inv.PDFUrl, inv.HostedURL,
		inv.IsPlanChange, inv.PlanChangeCtx, inv.CreatedAt,
	)
	if err != nil {
		return fmt.Errorf("billing: upsert invoice %s: %w", inv.ProviderID, err)
	}
	return nil
}

// GetInvoicesForOrg retrieves a paginated set of invoices for the specified organization.
func (s *InvoiceStore) GetInvoicesForOrg(ctx context.Context, orgID string, page, pageSize int) (*InvoicePage, error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	offset := (page - 1) * pageSize

	// Count total rows
	var total int
	err := s.pool.QueryRow(ctx, `SELECT COUNT(*) FROM invoices WHERE org_id = $1`, orgID).Scan(&total)
	if err != nil {
		return nil, fmt.Errorf("billing: count invoices for org %s: %w", orgID, err)
	}

	// Retrieve items page
	rows, err := s.pool.Query(ctx, `
		SELECT id, provider_id, provider_name, status, amount_cents, currency,
			description, invoice_number, pdf_url, hosted_url,
			is_plan_change, plan_change_ctx, created_at
		FROM invoices
		WHERE org_id = $1
		ORDER BY created_at DESC
		LIMIT $2 OFFSET $3
	`, orgID, pageSize, offset)
	if err != nil {
		return nil, fmt.Errorf("billing: list invoices for org %s: %w", orgID, err)
	}
	defer rows.Close()

	items := make([]InvoiceItem, 0)
	for rows.Next() {
		var (
			id, providerID, providerName, status, currency string
			amountCents                                    int
			description, invoiceNumber, pdfURL, hostedURL  sql.NullString
			isPlanChange                                   bool
			planChangeCtx                                  sql.NullString
			createdAt                                      time.Time
		)
		if err := rows.Scan(
			&id, &providerID, &providerName, &status, &amountCents, &currency,
			&description, &invoiceNumber, &pdfURL, &hostedURL,
			&isPlanChange, &planChangeCtx, &createdAt,
		); err != nil {
			return nil, fmt.Errorf("billing: scan invoice: %w", err)
		}

		items = append(items, InvoiceItem{
			ID:            id,
			Status:        status,
			AmountCents:   amountCents,
			Currency:      currency,
			CreatedAt:     createdAt.Format(time.RFC3339),
			HostedURL:     hostedURL.String,
			PDFUrl:        pdfURL.String,
			Description:   description.String,
			InvoiceNumber: invoiceNumber.String,
			IsPlanChange:  isPlanChange,
			PlanChangeCtx: planChangeCtx.String,
		})
	}

	return &InvoicePage{
		Invoices: items,
		Total:    total,
		Page:     page,
		PageSize: pageSize,
		HasMore:  offset+pageSize < total,
	}, nil
}

// GetInvoiceByID fetches a single local invoice by organization and ID.
func (s *InvoiceStore) GetInvoiceByID(ctx context.Context, orgID, invoiceID string) (*InvoiceItem, error) {
	var (
		id, status, currency                          string
		amountCents                                   int
		description, invoiceNumber, pdfURL, hostedURL sql.NullString
		isPlanChange                                  bool
		planChangeCtx                                 sql.NullString
		createdAt                                     time.Time
	)

	err := s.pool.QueryRow(ctx, `
		SELECT id, status, amount_cents, currency,
			description, invoice_number, pdf_url, hosted_url,
			is_plan_change, plan_change_ctx, created_at
		FROM invoices
		WHERE id = $1 AND org_id = $2
	`, invoiceID, orgID).Scan(
		&id, &status, &amountCents, &currency,
		&description, &invoiceNumber, &pdfURL, &hostedURL,
		&isPlanChange, &planChangeCtx, &createdAt,
	)
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("billing: get invoice %s: %w", invoiceID, err)
	}

	return &InvoiceItem{
		ID:            id,
		Status:        status,
		AmountCents:   amountCents,
		Currency:      currency,
		CreatedAt:     createdAt.Format(time.RFC3339),
		HostedURL:     hostedURL.String,
		PDFUrl:        pdfURL.String,
		Description:   description.String,
		InvoiceNumber: invoiceNumber.String,
		IsPlanChange:  isPlanChange,
		PlanChangeCtx: planChangeCtx.String,
	}, nil
}

// SyncInvoiceFromProvider maps a NormalizedInvoice to the local schema and upserts it.
func (s *InvoiceStore) SyncInvoiceFromProvider(ctx context.Context, orgID string, providerName ProviderName, inv NormalizedInvoice) error {
	local := LocalInvoice{
		OrgID:        orgID,
		ProviderID:   inv.ID,
		ProviderName: string(providerName),
		Status:       inv.Status,
		AmountCents:  inv.AmountCents,
		Currency:     inv.Currency,
		IsPlanChange: inv.IsPlanChange,
		CreatedAt:    inv.CreatedAt,
	}
	if inv.Description != "" {
		local.Description = sql.NullString{String: inv.Description, Valid: true}
	}
	if inv.InvoiceNumber != "" {
		local.InvoiceNumber = sql.NullString{String: inv.InvoiceNumber, Valid: true}
	}
	if inv.PDFUrl != "" {
		local.PDFUrl = sql.NullString{String: inv.PDFUrl, Valid: true}
	}
	if inv.HostedURL != "" {
		local.HostedURL = sql.NullString{String: inv.HostedURL, Valid: true}
	}
	if inv.PlanChangeCtx != "" {
		local.PlanChangeCtx = sql.NullString{String: inv.PlanChangeCtx, Valid: true}
	}

	if err := s.UpsertInvoice(ctx, local); err != nil {
		log.Error().Err(err).
			Str("org_id", orgID).
			Str("provider_id", inv.ID).
			Msg("billing: failed to sync invoice from provider")
		return err
	}

	log.Info().
		Str("org_id", orgID).
		Str("provider_id", inv.ID).
		Str("provider", string(providerName)).
		Msg("billing: invoice synced from provider")

	return nil
}
